spring:
  application:
    name: template # 애플리케이션 이름
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: core-db-pool

  jpa:
    open-in-view: false # Open EntityManager 설정 비활성화
    hibernate:
      ddl-auto: none # DDL 자동 실행 비활성화
    properties:
      hibernate:
        timezone.default_storage: NORMALIZE_UTC # Hibernate 기본 타임존 저장 방식
        jdbc.time_zone: UTC # JDBC 타임존 설정