spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      username: testuser
      password: testpass
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 20000

  jpa:
    show-sql: true # SQL 출력 활성화
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅 활성화