spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://prod-server:3306/proddb?useSSL=true&allowPublicKeyRetrieval=false&characterEncoding=UTF-8
      username: produser
      password: prodpass
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 120000
      connection-timeout: 5000

  jpa:
    show-sql: false # SQL 출력 비활성화